### PR TITLE
Added cross-platform Qt backend support, including MacOS.

### PR DESCRIPTION
**Pull request by orlp**
Pretty much title. Should be portable across Qt versions by detecting what matplotlib is using.

### CODE REVIEW

**Comment by joshburnett** [comment]
Thanks so much for your contribution! I've been crazy busy for the last few weeks (work & travel). I should be able to take a look at your PR in the next couple of weeks.

**Comment by joshburnett** [comment]
So sorry for taking so long to get around to reviewing your PR. I'm trying to get the code to work on my Mac and am running into various issues.

1. Can you tell me what version of Python, Matplotlib, and PyQt/PySide you've tested this with?
2. Are you explicitly selecting a particular backend? When I try w/ Python 3.9, Matplotlib 3.5.2 (latest), and PyQt5 or PyQt6, Matplotlib automatically selects the 'MacOSX' backend.
3. When I tell matplotlib to use qtagg, then your code fails on `qtver = matplotlib.backends.qt_compat.QT_API`, raising `AttributeError: module 'matplotlib' has no attribute 'backends'`.

**Comment by orlp** [comment]
```python
Python 3.10.2 (main, Mar  8 2022, 15:37:55) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('qtagg')
>>> import addcopyfighandler
>>> matplotlib.__version__
'3.5.1'
>>> qt = matplotlib.backends.qt_compat
>>> qt.QT_API
'PyQt6'
>>> qt.__version__
'6.2.3'
```

**Comment by joshburnett** [comment]
I set up a new venv w/ Python 3.10, matplotlib 3.5.1 and PyQt6. Still getting the error:

```
Python 3.10.3 (main, Mar 20 2022, 03:41:56) [Clang 13.0.0 (clang-1300.0.27.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('qtagg')
>>> matplotlib.backends.qt_compat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josh/code/addcopyfighandler/.venv-py310-pyqt6/lib/python3.10/site-packages/matplotlib/_api/__init__.py", line 222, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'backends'
>>> matplotlib.__version__
'3.5.1'
```

**Comment by joshburnett** [comment]
Wait... if I run pyplot.get_backend(), it now can resolve matplotlib.backends. So weird. I'll plugging away at it.

**Comment by JSpenced** [comment]
Any updates to this as I would like to use this on `macosx`?

**Comment by joshburnett** [comment]
Finally revisiting this! I found this reference that helps me get the matplotlib.backends bit working properly:

https://github.com/matplotlib/matplotlib/issues/18022

Looks like I just need to specifically `import matplotlib.backends`.

**Comment by joshburnett** [comment]
I implemented your changes (along with a few other things) today. MacOS support works fine now. Thanks so much for your efforts @orlp, even if it took me a year and a half to get them in! New package is available at PyPI now.

**Pull request closed without merging**
